export const  NEWVENDOR_REQUEST = "NEWVENDOR_REQUEST";
export const  NEWVENDOR_SUCCESS = "NEWVENDOR_SUCCESS";
export const  NEWVENDOR_FAIL = "NEWVENDOR_FAIL";
export const  NEWVENDOR_RESET = "NEWVENDOR_RESET";

export const  ALLUSERS_REQUEST = "ALLUSERS_REQUEST";
export const  ALLUSERS_SUCCESS = "ALLUSERS_SUCCESS";
export const  ALLUSERS_FAIL = "ALLUSERS_FAIL";


export const  PENDINGPRODUCT_REQUEST = "PENDINGPRODUCT_REQUEST";
export const  PENDINGPRODUCT_SUCCESS = "PENDINGPRODUCT_SUCCESS";
export const  PENDINGPRODUCT_FAIL = "PENDINGPRODUCT_FAIL";


export const  ACCEPTPRODUCT_REQUEST = "ACCEPTPRODUCT_REQUEST";
export const  ACCEPTPRODUCT_SUCCESS = "ACCEPTPRODUCT_SUCCESS";
export const  ACCEPTPRODUCT_FAIL = "ACCEPTPRODUCT_FAIL";
export const  ACCEPTPRODUCT_RESET = "ACCEPTPRODUCT_RESET";


export const  UPDATEUSER_REQUEST = "UPDATEUSER_REQUEST";
export const  UPDATEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const  UPDATEUSER_FAIL = "UPDATEUSER_FAIL";
export const  UPDATEUSER_RESET = "UPDATEUSER_RESET";

export const  DELETEUSER_REQUEST = "DELETEUSER_REQUEST";
export const  DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";
export const  DELETEUSER_FAIL = "DELETEUSER_FAIL";
export const  DELETEUSER_RESET = "DELETEUSER_RESET";