export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";


export const NEWPRODUCT_REQUEST = "NEWPRODUCT_REQUEST";
export const NEWPRODUCT_SUCCESS = "NEWPRODUCT_SUCCESS";
export const NEWPRODUCT_FAIL = "NEWPRODUCT_FAIL";
export const NEWPRODUCT_RESET = "NEWPRODUCT_RESET";


export const APPROVEDPRODUCT_REQUEST = "APPROVEDPRODUCT_REQUEST";
export const APPROVEDPRODUCT_SUCCESS = "APPROVEDPRODUCT_SUCCESS";
export const APPROVEDPRODUCT_FAIL = "APPROVEDPRODUCT_FAIL";
// export const APPROVEDPRODUCT_RESET = "APPROVEDPRODUCT_RESET";

